# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Proyectos"
url = "/projects"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Sobre Mí"
url = "/about"
weight = 4

# footer menu
[[footer]]
name = "Sobre Mí"
url = "/about"
weight = 1

[[footer]]
name = "Proyectos"
url = "/projects"
weight = 2
